name: Push multi manifest

on:
  workflow_call:
    inputs:
      amd-image:
        required: true
        type: string
      arm-image:
        required: true
        type: string
      manifest-image:
        required: true
        type: string
      registry:
        required: false
        type: string
      environment:
        required: true
        type: string

jobs:
  push:
    name: handle-${{ inputs.manifest-image }}
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    steps:
#     if registry is not docker.io, use env DOMESTIC_DOCKER_USERNAME and DOMESTIC_DOCKER_PASSWORD
#     else use env DOCKER_USERNAME and DOCKER_PASSWORD
      - name: Print Operation environment
        run: |
          env
      - name: Login to domestic ${{ inputs.registry }}
        if: ${{ inputs.registry != 'docker.io' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOMESTIC_DOCKER_USERNAME }}
          password: ${{ secrets.DOMESTIC_DOCKER_PASSWORD }}
          registry: ${{ inputs.registry }}
      - name: Login to ${{ inputs.registry }}
        if: ${{ inputs.registry == 'docker.io' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ inputs.registry }}

      - name: Create manifest
        run: |
          docker manifest create ${{ inputs.manifest-image }} ${{ inputs.amd-image }} ${{ inputs.arm-image }}
      - name: Push manifest
        run: |
          docker manifest push ${{ inputs.manifest-image }}
