name: Scheduled automatic packaging
on:
  repository_dispatch:
    types:
      - GitHub
      - GitLab

jobs:
  build-ui:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Build the Docker image
        env:
          BUILD_RBD_APP_UI: false
          TRAVIS_PULL_REQUEST: false
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAMESPACE: ${{ vars.IMAGE_NAMESPACE }}
          VERSION: ${{ github.event.client_payload.version }}
        run: |
          if [ ${{ github.event.action }} == 'GitHub' ];then
            git clone -b ${{ github.event.client_payload.branch }} ${{ github.event.client_payload.clone_url }}/rainbond-ui.git
          else
            git clone -b ${{ github.event.client_payload.branch }} ${{ github.event.client_payload.clone_url }}/rainbond-ui-cloud.git
          fi
          cd rainbond-ui
          chmod +x ./build.sh
          ./build.sh

  build-rainbond-allinone:
    needs: build-ui
    runs-on: ubuntu-20.04
    environment: production
    steps:
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 yapf==0.26.0

      - name: Pull code and Build allinone image
        env:
          VERSION: ${{ github.event.client_payload.version }}
          TRAVIS_PULL_REQUEST: false
          DOMESTIC_NAMESPACE: ${{ vars.DOMESTIC_NAMESPACE }}
          DOMESTIC_DOCKER_PASSWORD: ${{ secrets.DOMESTIC_DOCKER_PASSWORD }}
          DOMESTIC_DOCKER_USERNAME: ${{ secrets.DOMESTIC_DOCKER_USERNAME }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAMESPACE: ${{ vars.IMAGE_NAMESPACE }}
          DOMESTIC_BASE_NAME: ${{ vars.DOMESTIC_BASE_NAME }}
          ADAPTOR_BRANCH: ${{ vars.ADAPTOR_BRANCH}}
        run: |
          if [ ${{ github.event.action }} == 'GitHub' ];then
            git clone -b ${{ github.event.client_payload.branch }} ${{ github.event.client_payload.clone_url }}/rainbond-console.git
          else
            git clone -b ${{ github.event.client_payload.branch }} ${{ github.event.client_payload.clone_url }}/rainbond-console-cloud.git
          fi
          cd rainbond-console
          chmod +x  ./release.sh
          ./release.sh allinone

  build-rainbond-region:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: 1.18

      - name: Pull code and Build the Docker image
        env:
          VERSION: ${{ github.event.client_payload.version }}
          DISABLE_GOPROXY: true
          DOMESTIC_BASE_NAME: ${{ vars.DOMESTIC_BASE_NAME }}
          IMAGE_NAMESPACE: ${{ vars.IMAGE_NAMESPACE }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOMESTIC_DOCKER_PASSWORD: ${{ secrets.DOMESTIC_DOCKER_PASSWORD }}
          DOMESTIC_DOCKER_USERNAME: ${{ secrets.DOMESTIC_DOCKER_USERNAME }}
          DOMESTIC_NAMESPACE: ${{ vars.DOMESTIC_NAMESPACE }}
        run: |
          if [ ${{ github.event.action }} == 'GitHub' ];then
            git clone -b ${{ github.event.client_payload.branch }} ${{ github.event.client_payload.clone_url }}/rainbond.git
          else
            git clone -b ${{ github.event.client_payload.branch }} ${{ github.event.client_payload.clone_url }}/rainbond.git
          fi
          cd rainbond
          chmod +x ./release.sh
          ./release.sh api push

  build-rainbond-region-chaos:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: 1.18

      - name: Pull code and Build the Docker image
        env:
          VERSION: ${{ github.event.client_payload.version }}
          DISABLE_GOPROXY: true
          DOMESTIC_BASE_NAME: ${{ vars.DOMESTIC_BASE_NAME }}
          IMAGE_NAMESPACE: ${{ vars.IMAGE_NAMESPACE }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOMESTIC_DOCKER_PASSWORD: ${{ secrets.DOMESTIC_DOCKER_PASSWORD }}
          DOMESTIC_DOCKER_USERNAME: ${{ secrets.DOMESTIC_DOCKER_USERNAME }}
          DOMESTIC_NAMESPACE: ${{ vars.DOMESTIC_NAMESPACE }}
        run: |
          if [ ${{ github.event.action }} == 'GitHub' ];then
            git clone -b ${{ github.event.client_payload.branch }} ${{ github.event.client_payload.clone_url }}/rainbond.git
          else
            git clone -b ${{ github.event.client_payload.branch }} ${{ github.event.client_payload.clone_url }}/rainbond.git
          fi
          cd rainbond
          chmod +x ./release.sh
          ./release.sh chaos push

  build-operator:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: 1.18

      - name: Build and push
        env:
          IMAGE_NAMESPACE: ${{ vars.IMAGE_NAMESPACE }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOMESTIC_DOCKER_PASSWORD: ${{ secrets.DOMESTIC_DOCKER_PASSWORD }}
          DOMESTIC_DOCKER_USERNAME: ${{ secrets.DOMESTIC_DOCKER_USERNAME }}
          DOMESTIC_BASE_NAME: ${{ vars.DOMESTIC_BASE_NAME }}
          DOMESTIC_NAMESPACE: ${{ vars.DOMESTIC_NAMESPACE }}
          VERSION: ${{ github.event.client_payload.version }}
        run: |
          echo ${DOCKER_USERNAME}
          echo ${{ vars.DOCKER_USERNAME }}
          echo ${{ secrets.DOCKER_USERNAME }}
          git clone -b ${{ vars.OPERATOR_BRANCH }} ${{ github.event.client_payload.clone_url }}/rainbond-operator.git
          cd rainbond-operator
          chmod +x ./release.sh
          ./release.sh

  build-dind:
    needs: [build-ui,build-rainbond-region,build-operator]
    runs-on: ubuntu-20.04
    environment: production
    if: ${{ github.event.action }} == 'GitHub'
    steps:
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 yapf==0.26.0
      - name: Pack offline packages
        env:
          IMAGE_NAMESPACE: ${{ vars.IMAGE_NAMESPACE }}
          RBD_VER: ${{ github.event.client_payload.version }}
          TRAVIS_PULL_REQUEST: false
          DOMESTIC_NAMESPACE: ${{ vars.DOMESTIC_NAMESPACE }}
          DOMESTIC_BASE_NAME: ${{ vars.DOMESTIC_BASE_NAME }}
        run: |
          git clone -b ${{ github.event.client_payload.branch }} ${{ github.event.client_payload.clone_url }}/rainbond-console.git   
          cd rainbond-console
          chmod +x ./release.sh
      - name: Build the Docker image
        env:
          TRAVIS_PULL_REQUEST: false
          IMAGE_NAMESPACE: ${{ vars.IMAGE_NAMESPACE }}
          BUILD_IMAGE_NAMESPACE: ${{ vars.BUILD_IMAGE_NAMESPACE }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOMESTIC_NAMESPACE: ${{ vars.DOMESTIC_NAMESPACE }}
          DOMESTIC_DOCKER_PASSWORD: ${{ secrets.DOMESTIC_DOCKER_PASSWORD }}
          DOMESTIC_DOCKER_USERNAME: ${{ secrets.DOMESTIC_DOCKER_USERNAME }}
          VERSION: ${{ github.event.client_payload.version }}
          OPERATOR_BRANCH: ${{ vars.OPERATOR_BRANCH }}
          ADAPTOR_BRANCH: ${{ vars.ADAPTOR_BRANCH }}
        run: |
          cd rainbond-console
          ./release.sh dind
